import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Mahesh',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('Mahi', 8),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
      
      {
        //_id: '2',
        name: 'Laptop',
        category: 'ALL',
        image: '/images/newlaptop.jpg',
        price: 22000,
        countInStock:2,
        brand: 'DELL',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
       // _id: '3',
        name: 'Apple Laptop',
        category: 'Computer',
        image: '/images/newlaptop2.jpg',
        price: 25000,
        countInStock:2,
        brand: 'HP',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        //_id: '4',
        name: 'Arduino',
        category: 'Computer',
        image: '/images/arduinonew.jpg',
        price: 300,
        countInStock:2,
        brand: 'Dell',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        //_id: '5',
        name: 'Keyboard',
        category: 'Computer',
        image: '/images/newkeyboard.jpg',
        price: 120,
        countInStock:2,
        brand: 'Acer',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
       // _id: '6',
        name: 'Container',
        category: 'Drawing',
        image: '/images/newcontainer.jpg',
        price: 30,
        countInStock:2,
        brand: 'XYZ',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        // _id: '6',
         name: 'Bag',
         category: 'All',
         image: '/images/newbag.jpg',
         price: 175,
         countInStock:1,
         brand: 'XYZ',
         rating: 4.5,
         numReviews: 11,
         description: 'high quality product',
       },
       {
        // _id: '6',
         name: 'Mouse',
         category: 'Computer',
         image: '/images/newmouse.jpg',
         price: 90,
         countInStock:2,
         brand: 'XYZ',
         rating: 4.5,
         numReviews: 7,
         description: 'high quality product',
       },
       {
        // _id: '6',
         name: 'C++ Book',
         category: 'Book',
         image: '/images/newcppbook.jpg',
         price: 200,
         countInStock:1,
         brand: 'XYZ',
         rating: 4.5,
         numReviews: 15,
         description: 'high quality product',
       },
       {
        //  _id: '1',
          name: 'Drafter',
          category: 'Drawing',
          image: '/images/drafter.jpg',
          price: 120,
          countInStock:1,
          brand: 'XYZ',
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
    ],
  };
  export default data;