const data = {
    products: [
      {
        _id: '1',
        name: 'Drafter',
        category: 'Drawing',
        image: '/images/drafter.jpg',
        price: 120,
        countInStock:1,
        brand: 'XYZ',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Bag',
        category: 'ALL',
        image: '/images/drafter.jpg',
        price: 100,
        countInStock:2,
        brand: 'DELL',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Laptop',
        category: 'Computer',
        image: '/images/drafter.jpg',
        price: 220,
        countInStock:2,
        brand: 'HP',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Mouse',
        category: 'Computer',
        image: '/images/drafter.jpg',
        price: 78,
        countInStock:2,
        brand: 'Dell',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Keyboard',
        category: 'Computer',
        image: '/images/drafter.jpg',
        price: 65,
        countInStock:2,
        brand: 'Acer',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Container',
        category: 'Drawing',
        image: '/images/drafter.jpg',
        price: 139,
        countInStock:2,
        brand: 'XYZ',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;